### ISSUE TITLE
Gaia-X Walt.id Demo Flow not working

### ISSUE THREAD

**Issue by kaimeinke** [gaiax-waltid/gaiax-waltid-docs#1]
Reproduction:

iOS, Brave, MetaMask

https://gaiax-portal.walt.id/ aufrufen und Wallet verbinden

ok.

login with auth-ok@example.com ein.

Error: No Credentials found!

![image](https://user-images.githubusercontent.com/59994024/152161965-991d1770-aeb7-41b8-87dd-516c9f19ef46.png)

Going back one page ... some credentials are shown, but I can't use them.

![image](https://user-images.githubusercontent.com/59994024/152162011-dfa997d7-0b26-47c8-ba91-410e445f80cd.png)

Revisiting the sign-in page the login in the wallet is forgotten.

**Comment by philpotisk** [comment]
@kaimeinke I could reconstruct this issue. The problem is that on default the "did:key" ecosystem is selected, but the required Credential is associated to did:ebsi. So you would need to select the right did (Settings -> Ecosystems -> EBSI/ESSIF -> select did:ebsi:...) before running the authentication flow.

![image](https://user-images.githubusercontent.com/55081379/152211800-d739133e-dc09-4095-811e-f20936ed46f2.png)

Regarding the "lost" login: Well the authentication-part is for this demo-purpose not enabled. We will add a disclaimer for explaining this.
